# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1338056358);
user_pref("app.update.lastUpdateTime.background-update-timer", 1338056358);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1338056358);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1338056358);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 1048576);
user_pref("browser.dom.window.dump.enabled", true);
user_pref("browser.migration.version", 6);
user_pref("browser.places.smartBookmarksVersion", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.0.gethashURL", "http://localhost/safebrowsing-dummy/gethash");
user_pref("browser.safebrowsing.provider.0.keyURL", "http://localhost/safebrowsing-dummy/newkey");
user_pref("browser.safebrowsing.provider.0.updateURL", "http://localhost/safebrowsing-dummy/update");
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "http://forums.somethingawful.com/");
user_pref("browser.startup.homepage_override.buildID", "20120516113045");
user_pref("browser.startup.homepage_override.mstone", "13.0");
user_pref("browser.syncPromoViewsLeft", 4);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("browser.warnOnQuit", false);
user_pref("devtools.errorconsole.enabled", true);
user_pref("devtools.inspector.sidebarOpen", true);
user_pref("extensions.autoDisableScopes", 10);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.blocklist.url", "http://localhost/extensions-dummy/blocklistURL");
user_pref("extensions.bootstrappedAddons", "{\"jid1-m0mwMl2WzzlyMA@jetpack\":{\"version\":\"0.1.6\",\"type\":\"extension\",\"descriptor\":\"H:\\\\Documents\\\\GitHub\\\\FancySA\\\\test-profile\\\\extensions\\\\jid1-m0mwMl2WzzlyMA@jetpack.xpi\"}}");
user_pref("extensions.checkCompatibility.13.0", false);
user_pref("extensions.checkCompatibility.nightly", false);
user_pref("extensions.databaseSchema", 12);
user_pref("extensions.enabledAddons", "{972ce4c6-7e08-4474-a285-3208198ce6fd}:13.0");
user_pref("extensions.enabledScopes", 5);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1336791038537}}},{\"name\":\"app-profile\",\"addons\":{\"jid1-m0mwMl2WzzlyMA@jetpack\":{\"descriptor\":\"H:\\\\Documents\\\\GitHub\\\\FancySA\\\\test-profile\\\\extensions\\\\jid1-m0mwMl2WzzlyMA@jetpack.xpi\",\"mtime\":1338056237333}}}]");
user_pref("extensions.installDistroAddons", false);
user_pref("extensions.lastAppVersion", "13.0");
user_pref("extensions.lastPlatformVersion", "13.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.testpilot.runStudies", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("extensions.update.url", "http://localhost/extensions-dummy/updateURL");
user_pref("extensions.webservice.discoverURL", "http://localhost/extensions-dummy/discoveryURL");
user_pref("general.warnOnAboutConfig", false);
user_pref("gfx.direct2d.disabled", true);
user_pref("idle.lastDailyNotification", 1338057089);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("javascript.options.strict", true);
user_pref("layers.acceleration.disabled", true);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1338057089);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("startup.homepage_welcome_url", "about:blank");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1338057089);
user_pref("toolkit.startup.last_success", 1338056237);
user_pref("toolkit.telemetry.prompted", 2);
user_pref("urlclassifier.keyupdatetime.http://localhost/safebrowsing-dummy/newkey", 1340648446);
user_pref("urlclassifier.updateinterval", 172800);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
